# Generated by Django 2.2.2 on 2020-01-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200108_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(related_name='news_categories', to='news.Category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
